# Generated by Django 3.0.14 on 2023-08-13 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order_data',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('timeStamp', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('parent_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
