# Generated by Django 3.0.14 on 2023-08-02 09:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='r_attribute',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_line', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_registration', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/images')),
                ('opening_time', models.CharField(blank=True, max_length=50, null=True)),
                ('closing_time', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500)),
                ('pin_code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)])),
                ('guardian_phone_number', models.CharField(max_length=11)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time_to_cook_in_minutes', models.IntegerField(default=15)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/images')),
                ('in_stock', models.BooleanField(default=False)),
                ('by_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='c_attribute',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
