# Generated by Django 3.0.14 on 2023-08-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='r_attribute',
            old_name='Address',
            new_name='address',
        ),
    ]
