# Generated by Django 3.0.14 on 2023-08-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0002_auto_20230802_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_attribute',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
