# Generated by Django 3.0.14 on 2023-08-06 19:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market_place', '0003_r_attribute_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='running_visitor_orders',
            fields=[
                ('dynamic_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered_ids', models.CharField(max_length=5000)),
                ('cost', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500)),
                ('pin_code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)])),
                ('delivery_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='c_attribute',
            name='City',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='c_attribute',
            name='State',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='c_attribute',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='c_attribute',
            name='pin_code',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)]),
        ),
        migrations.CreateModel(
            name='running_orders',
            fields=[
                ('dynamic_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered_ids', models.CharField(max_length=5000)),
                ('cost', models.IntegerField()),
                ('delivery_status', models.BooleanField(default=False)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
