# Generated by Django 3.0.14 on 2023-08-06 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0004_auto_20230807_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_attribute',
            name='City',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='c_attribute',
            name='State',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='c_attribute',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='c_attribute',
            name='pin_code',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)]),
        ),
    ]
