# Generated by Django 3.0.14 on 2023-08-06 19:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market_place', '0005_auto_20230807_0108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='running_orders',
            new_name='orders',
        ),
        migrations.RenameModel(
            old_name='running_visitor_orders',
            new_name='visitor_orders',
        ),
    ]
