# Generated by Django 3.0.14 on 2023-08-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0006_auto_20230807_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='visitor_orders',
        ),
    ]
