# Generated by Django 3.0.14 on 2023-08-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0008_auto_20230807_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_ids',
        ),
        migrations.RemoveField(
            model_name='r_attribute',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='r_attribute',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='order',
            name='name_of_those_restaurants',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurants_per_order',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='sub_order',
            fields=[
                ('sub_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered_ids', models.CharField(max_length=3000)),
                ('cost', models.IntegerField()),
                ('delivery_status', models.BooleanField(default=False)),
                ('parent_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_place.order')),
            ],
        ),
    ]
