# Generated by Django 3.0.14 on 2023-08-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0009_auto_20230811_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name_of_those_restaurants',
            field=models.TextField(),
        ),
    ]
