# Generated by Django 3.0.14 on 2023-08-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0010_auto_20230811_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='net_delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
