# Generated by Django 3.0.14 on 2023-08-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0011_order_net_delivery_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurants_per_order',
            new_name='total_restaurants_associated',
        ),
    ]
