# Generated by Django 3.0.14 on 2023-08-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0012_auto_20230812_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_order',
            name='Preparation_time_in_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
