# Generated by Django 3.0.14 on 2023-08-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0013_sub_order_preparation_time_in_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_order',
            old_name='Preparation_time_in_minutes',
            new_name='preparation_time_in_minutes',
        ),
    ]
