# Generated by Django 3.0.14 on 2023-08-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0014_auto_20230812_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_order',
            name='preparation_time_in_minutes',
            field=models.IntegerField(),
        ),
    ]
