# Generated by Django 3.0.14 on 2023-08-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0015_auto_20230812_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='time_to_cook_in_minutes',
            new_name='preparation_time_in_minutes',
        ),
    ]
