# Generated by Django 3.0.14 on 2023-08-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0016_auto_20230812_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_order',
            name='preparation_time_in_minutes',
        ),
        migrations.AddField(
            model_name='sub_order',
            name='total_preparation_time_in_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
