# Generated by Django 3.0.14 on 2023-08-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0018_auto_20230812_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_order',
            name='preparation_status',
            field=models.BooleanField(default=False),
        ),
    ]
