# Generated by Django 3.0.14 on 2023-08-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0019_sub_order_preparation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='feedback',
            field=models.IntegerField(default=0),
        ),
    ]
