# Generated by Django 3.0.14 on 2023-08-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0021_auto_20230813_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
