# Generated by Django 3.0.14 on 2023-08-13 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0022_auto_20230813_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sub_order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
