# Generated by Django 3.0.14 on 2023-08-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0023_auto_20230813_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AlterField(
            model_name='sub_order',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
