# Generated by Django 3.0.14 on 2023-08-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0024_auto_20230813_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
