# Generated by Django 3.0.14 on 2023-08-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0025_auto_20230814_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_attribute',
            name='closing_time_hours',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='r_attribute',
            name='opening_time_hours',
            field=models.IntegerField(default=9),
        ),
    ]
