# Generated by Django 3.0.14 on 2023-08-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0027_auto_20230815_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=50),
        ),
    ]
