# Generated by Django 3.0.14 on 2023-08-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0028_auto_20230815_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
