# Generated by Django 3.0.14 on 2023-08-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0029_food_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_attribute',
            name='restaurant_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
