# Generated by Django 3.0.14 on 2023-08-15 05:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market_place', '0032_auto_20230815_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_attribute',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('security_key', models.IntegerField(default=24681357, validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(10000000)])),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
