# Generated by Django 3.0.14 on 2023-08-15 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market_place', '0034_auto_20230815_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_Confirmation',
            fields=[
                ('otp_confirmation_id', models.AutoField(primary_key=True, serialize=False)),
                ('confirmation_status', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
