# Generated by Django 3.0.14 on 2023-08-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0036_remove_r_attribute_date_of_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_attribute',
            name='parent_ki_id',
            field=models.IntegerField(default=0),
        ),
    ]
